### ISSUE TITLE
Theme Compatibility: Twenty Twenty

### ISSUE THREAD

**Issue by seb86** [pixelbart/helpful#19]
Any chance this is a bug? Should really be centered not to the left side.

Helpful theme: Base.

Please support Twenty Twenty theme.

![image](https://user-images.githubusercontent.com/497406/135903688-61f000fe-5775-4da8-9af0-b6b39681d725.png)

If you need any additional details please let me know.

Thank you.

**Comment by pixelbart** [comment]
@seb86 

This is not a problem of Helpful, but of the theme. The theme requires all content to be centered, so the solution to the problem is individual.

You can enter the following in the Customizer and "Custom CSS" and solve the problem:

```css
.helpful {
    margin-left: auto;
    margin-right: auto;
}
```

**Comment by seb86** [comment]
Well the helpful container is within the entry-content container and that is centered. Removing the margin applied to .helpful class would make a difference as it will be aligning correctly to the theme.

However, I have already dealt with the CSS and applied a font size correction too.

```css
.helpful,
.helpful .helpful-content .helpful-button,
.helpful > .helpful-controls > div > .helpful-button,
.helpful .helpful-feedback-controls .helpful-button {
    font-size: 1.4rem;
}

.helpful > .helpful-content {
	font-size: 2.1rem;
	line-height: 1.5;
}
```

To enhance the styling issue you could provide more theme customize options for alignment and font-size but by default allow your helpful CSS to inherit the theme styling more no matter the theme selected.

Just my feedback so far for your plugin which is working well so far. So thanks.
